FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /auth ./cmd/auth

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /auth /auth
COPY configs/auth.yaml /configs/auth.yaml
EXPOSE 8081
CMD ["/auth"]