FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /media ./cmd/media

FROM alpine:3.19
RUN apk --no-cache add ca-certificates ffmpeg
COPY --from=builder /media /media
COPY configs/media.yaml /configs/media.yaml
EXPOSE 8083
CMD ["/media"]