FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /search ./cmd/search

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /search /search
COPY configs/search.yaml /configs/search.yaml
EXPOSE 8087
CMD ["/search"]