FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /call ./cmd/call

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /call /call
COPY configs/call.yaml /configs/call.yaml
EXPOSE 8084
CMD ["/call"]