FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bot ./cmd/bot

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /bot /bot
COPY configs/bot.yaml /configs/bot.yaml
EXPOSE 8085
CMD ["/bot"]